[package]
name = "binance-fix-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
binance-fix44-order-entry = { path = "../binance-fix44-order-entry", version = "0.1.0" }
hmac = "0.12.1"
quickfix = "0.2.0"
sha2 = "0.10.8"